### ISSUE TITLE
bug: `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)

### ISSUE THREAD

**Issue by fruwe** [dockage/mailcatcher#22]
#21 brakes mailcatcher due to missing dependencies.

```
docker run --name='mailcatcher' \
  --publish=1080:1080 \
  --publish=1025:1025 \
dockage/mailcatcher:0.9.0
```

outputs this log

```
Starting MailCatcher v0.9.0
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': Error relocating /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so: fcntl64: symbol not found - /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
```

**Comment by atkrad** [comment]
Hey @fruwe, Thanks for opening this issue.

Could you please test it with this command?
```shell
docker run --pull always --publish=1080:1080 --publish=1025:1025 -ti dockage/mailcatcher:0.9.0
``` 
It works for me.

**Comment by fruwe** [comment]
@atkrad Thanks for your quick response. For me and another team mate, we are getting this:

```
docker run --pull always --publish=1080:1080 --publish=1025:1025 -ti dockage/mailcatcher:0.9.0

0.9.0: Pulling from dockage/mailcatcher
Digest: sha256:5df6389c826af3e55929e2328b0d138dba446075e2796f83e5797fe364643667
Status: Image is up to date for dockage/mailcatcher:0.9.0
Starting MailCatcher v0.9.0
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:40:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
<internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require': Error relocating /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so: fcntl64: symbol not found - /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3/3.2/sqlite3_native.so (LoadError)
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/sqlite3-1.7.3-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from <internal:/usr/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	from /usr/lib/ruby/gems/3.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
	from /usr/lib/ruby/gems/3.2.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
	from /usr/bin/mailcatcher:25:in `load'
	from /usr/bin/mailcatcher:25:in `<main>'
```

We are using the latest docker desktop for MacOS (Apple Sillicon)

**Comment by fruwe** [comment]
(FYI, It was working until yesterday)

**Comment by atkrad** [comment]
Now, you can pull the image and test it again.
@fruwe, please let me know if everything is fine.

Thanks.

**Comment by fruwe** [comment]
@atkrad Wow, thank you for the quick fix, Mohammad. Everything is working perfectly now.
