### ISSUE TITLE
Container exits as soon as it is started

### ISSUE THREAD

**Issue by sarthikg** [dockage/mailcatcher#9]
## Docker Image Details:
- Name: `dockage/mailcatcher`
- ID: `d7896ae8993c870243b716db2d8ecf8bb31f203bc98f3c63bdee12e3ec3e1246`

## System Details:
- MacBook Air M2

## Startup Script:
It is being executed from the `docker-compose` setup:
```yaml
mailcatcher:
    image: dockage/mailcatcher:latest
    container_name: mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      SMTP_PORT: 1025
      SMTP_USERNAME: user@example.com
      SMTP_PASSWORD: password
```

## Error Details:
```
2023-10-13 14:22:22 Starting MailCatcher v0.9.0
2023-10-13 14:27:49 Starting MailCatcher v0.9.0
2023-10-13 14:22:22 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:22:22 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:22:22 from /usr/bin/mailcatcher:25:in `<main>'
2023-10-13 14:22:22 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so) - /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so (LoadError)
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:22:22 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:22:22 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:22:22 from /usr/bin/mailcatcher:25:in `<main>'
2023-10-13 14:27:49 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:27:49 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:27:49 from /usr/bin/mailcatcher:25:in `<main>'
2023-10-13 14:27:52 Starting MailCatcher v0.9.0
2023-10-13 14:27:49 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so) - /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so (LoadError)
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:27:49 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:27:49 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:27:49 from /usr/bin/mailcatcher:25:in `<main>'
2023-10-13 14:27:52 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sqlite3/sqlite3_native (LoadError)
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:6:in `rescue in <top (required)>'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:2:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:27:52 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:27:52 from /usr/bin/mailcatcher:25:in `<main>'
2023-10-13 14:27:52 <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so) - /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3/3.1/sqlite3_native.so (LoadError)
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/sqlite3-1.6.3-aarch64-linux/lib/sqlite3.rb:4:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/mail.rb:6:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher/smtp.rb:5:in `<top (required)>'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:183:in `block (2 levels) in run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:239:in `rescue_port'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:182:in `block in run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/lib/mail_catcher.rb:180:in `run!'
2023-10-13 14:27:52 from /usr/lib/ruby/gems/3.1.0/gems/mailcatcher-0.9.0/bin/mailcatcher:6:in `<top (required)>'
2023-10-13 14:27:52 from /usr/bin/mailcatcher:25:in `load'
2023-10-13 14:27:52 from /usr/bin/mailcatcher:25:in `<main>'
```

**Comment by sarthikg** [comment]
I was earlier using this image on a windows machine with WSL. It was somehow working correctly there. I am assuming this error is specific to MacOS or Apple-Silicon.

**Comment by lucaferri** [comment]
I had the same problem but I manage to solve it (Macbook Air M1)

```yaml
mailcatcher:
    platform: linux/x86_64
    image: dockage/mailcatcher:latest
    ports:
      - "1025:1025"
      - "1080:1080"
```

`platform: linux/x86_64` did the trick

**Comment by lucagouty** [comment]
I tried v0.8 and v0.9 on both M2 Apple Silicon and Raspberry PI 4 and the issue occurs.

I'm guessing those are affected on https://hub.docker.com/r/dockage/mailcatcher/tags
- linux/arm/v6
- linux/arm/v7
- linux/arm64

For Apple Silicon we can use rosetta and x86 image but on other ARM based computer there's no workaround afaik

**Comment by atkrad** [comment]
The issue has been resolved.
